language: node_js
node_js:
  - '6'
  - '8'
  - '9'
after_success: npm run coveralls
deploy:
  provider: npm
  email: nwoltman@outlook.com
  on:
    tags: true
  api_key:
    secure: c6pdfFCT0Os43bXSfCuMMOYPBBVj7LEeh3eiHHYdJCHCzZwQZqOODTZ04Ov9vGH857q90DaIpEO4TbTA7zbJjibnc8SSO75568YZ7V79heD274h8KjVwG1c4UDEbjinj900qRTd8qpOhlJO3Rf6GHin+ZXY76sSmzcdvvJKfvXkYz9OPcwCcf51QykXI6pHWaWOs1r4Zwvr/0t7mXg9zRCWsFffA0zBQfQ2/8Cx/AAhgirq6k9qt3Cw1ahuOWfHhRKC9fJujZWLvsBXHLPD1pF8QxwSmol+GWSkp/wI89gIFUM4sIDjw+EeZ6FIvrnTkw47tFsDsWdHeZQzYWtQHPMC9yx4UhpaHmukuo1XvMycidFX8tSwsywbO4Exa4IS31U7eS1s2CDW0sVLDu4tkFVyX8nFeSNse26NYGzRe9WBoB1OuSUiV7Z+x+xy83e/cG+YGugMlSQ9OgxLgmjavB9LlcHRP8NWCHwbdhq+RzCrSrCaF0s3pUGTQi6k0v4Rc8zQjMpMLFFbWFuAn6/A6IoIMdmtlUtuFXoTs4cVym+9XqsH/+hOVjZkkl4qrI5xwMY4ZKFnQ2Y9p/2S+r1ydulUZOJSreFGnD8/b9nt7+6Ld6DjQmKVqGlSOTxiiIhY7Z1bkVjQGtJYnKBXNadM77e4JD/YnbSN4hVVLZEQoEAY=
